version: 0.0
os: linux
files:
  - source: ./distribution
    destination: /var/www/html/dashboard/
    file_exists_behavior: OVERWRITE
hooks:
  BeforeInstall:
    - location: scripts/setup.sh
      timeout: 300
      runas: ubuntu